title = "Leaving everything, together"
baseURL = "https://www.leavehut.com"
languageCode = "en-us"
theme = "ananke"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "G-44S5MKE2BJ"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "Maybe you should leave too"
  twitter = "https://twitter.com/imleaving11"
  youtube = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 4
[taxonomies]
  tag = "tags"
